version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - WezSieTato
  - Dentro2000
  versioning-strategy: lockfile-only
