//
//  MNFSpendingChallenge.h
//  Meniga-ios-sdk
//
//  Created by Haukur Ísfeld on 13/01/17.
//  Copyright © 2017 Meniga. All rights reserved.
//

#import "MNFObject.h"

NS_ASSUME_NONNULL_BEGIN

/**
 The MNFSpendingChallenge represents a suggested challenge generated by a server admin.
 */
@interface MNFSpendingChallenge : MNFObject

///******************************
/// @name Immutable properties
///******************************

/**
 The category ids of the categories for this challenge.
 */
@property (nonatomic, copy, readonly) NSArray *_Nullable categoryIds;

/**
 The target spending percentage of this challenge.
 */
@property (nonatomic, strong, readonly) NSNumber *_Nullable targetPercentage;

/**
 The spend amount of this challenge.
 */
@property (nonatomic, strong, readonly) NSNumber *_Nullable spentAmount;

/**
 The interval with which this challenge repeates.
 */
@property (nonatomic, strong, readonly) NSString *_Nullable recurringInterval;

/**
 The number of participants in this challenge.
 */
@property (nonatomic, strong, readonly) NSNumber *_Nullable numberOfParticipants;

///******************************
/// @name Mutable properties
///******************************

/**
 The target spending amount of this challenge.
 */
@property (nonatomic, strong) NSNumber *_Nullable targetAmount;

@end

NS_ASSUME_NONNULL_END
